ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('toko.urls', namespace='toko')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toko/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'toko'

urlpatterns = [
    path('', views.HomeListView.as_view(), name='home-produk-list'),
    path('contact/', views.contact, name='contact'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='produk-detail'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_method>/', views.PaymentView.as_view(), name='payment'),
    path('paypal-return/', views.paypal_return, name='paypal-return'),
    path('paypal-cancel/', views.paypal_cancel, name='paypal-cancel'),
    path('<str:category>/', views.HomeListView.as_view(), name='home_category'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toko/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from decimal import Decimal

PILIHAN_KATEGORI = (
    ('D', 'Dress'),
    ('S', 'Shirt'),
    ('SW', 'Sweatshirt'),
    ('C', 'pants'),
    ('Pl', 'Playsuit & Jumpsuit')
)

PILIHAN_LABEL = (
    ('NEW', 'primary'),
    ('SALE', 'info'),
    ('BEST', 'danger'),
)

PILIHAN_PEMBAYARAN = (
    ('P', 'Paypal'),
    ('S', 'Stripe'),
)

User = get_user_model()

class ProdukItem(models.Model):
    nama_produk = models.CharField(max_length=100)
    harga = models.DecimalField(max_digits=8, decimal_places=3, default=Decimal('6.00'))
    harga_diskon = models.DecimalField(max_digits=8, decimal_places=3,blank=True, null=True)
    slug = models.SlugField(unique=True)
    deskripsi = models.TextField()
    gambar = models.ImageField(upload_to='product_pics')
    label = models.CharField(choices=PILIHAN_LABEL, max_length=4)
    kategori = models.CharField(choices=PILIHAN_KATEGORI, max_length=2)

    def __str__(self):
        return f"{self.nama_produk} - ${self.harga}"

    def get_absolute_url(self):
        return reverse("toko:produk-detail", kwargs={
            "slug": self.slug
            })

    def get_add_to_cart_url(self):
        return reverse("toko:add-to-cart", kwargs={
            "slug": self.slug
            })
    
    def get_remove_from_cart_url(self):
        return reverse("toko:remove-from-cart", kwargs={
            "slug": self.slug
            })
    
    @property
    def get_price(self):
        if self.harga_diskon:
            return self.harga_diskon
        else:
            return self.harga
        
    @property
    def discount_percentage(self):
        if self.harga_diskon:
            return round(((self.harga - self.harga_diskon) / self.harga) * 100)
        else:
            return 0
    
class OrderProdukItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    produk_item = models.ForeignKey(ProdukItem, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.produk_item.nama_produk}"

    def get_total_harga_item(self):
        return self.quantity * self.produk_item.harga
    
    def get_total_harga_diskon_item(self):
        return self.quantity * self.produk_item.harga_diskon

    def get_total_hemat_item(self):
        return self.get_total_harga_item() - self.get_total_harga_diskon_item()
    
    def get_total_item_keseluruan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_harga_diskon_item()
        return self.get_total_harga_item()
    
    def get_total_hemat_keseluruhan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_hemat_item()
        return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    produk_items = models.ManyToManyField(OrderProdukItem)
    tanggal_mulai = models.DateTimeField(auto_now_add=True)
    tanggal_order = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    alamat_pengiriman = models.ForeignKey('AlamatPengiriman', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

     
    def get_total_harga_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_item_keseluruan()
        return total
    
    def get_total_hemat_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_hemat_keseluruhan()
        return total

class AlamatPengiriman(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    alamat_1 = models.CharField(max_length=100)
    alamat_2 = models.CharField(max_length=100)
    negara = models.CharField(max_length=100)
    kode_pos = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.user.username} - {self.alamat_1}"

    class Meta:
        verbose_name_plural = 'AlamatPengiriman'

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    payment_option = models.CharField(choices=PILIHAN_PEMBAYARAN, max_length=1)
    charge_id = models.CharField(max_length=50)

    def __self__(self):
        return self.user.username
    
    def __str__(self):
        return f"{self.user.username} - {self.payment_option} - {self.amount}"
    
    class Meta:
        verbose_name_plural = 'Payment'
        

from django.shortcuts import render, get_object_or_404
from .models import ProdukItem

def produk_detail(request, slug):
    produk = get_object_or_404(ProdukItem, slug=slug)

    # Mendapatkan produk terkait berdasarkan kategori produk yang sedang dibuka
    related_items = ProdukItem.objects.filter(kategori=produk.kategori).exclude(slug=produk.slug)[:3]

    context = {
        'produk': produk,
        'related_items': related_items
    }

    return render(request, 'toko/produk_detail.html', context)

ecomm/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>

    <title>Kumo {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" /> 
    <!-- MDB icon -->
    <link rel="icon" href="{% static 'img/logo' %}" type="image/x-icon" />
    <link rel="stylesheet"href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">       
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://kit.fontawesome.com/your-font-awesome-kit.js" crossorigin="anonymous"></script>
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <link rel="stylesheet" href="https://cdn.tailwindcss.com/2.2.17/tailwind.min.css">
  </head>
  <body>
    
    {% include 'navbar.html' %}
 

    <div class="mt-5 pt-4">
      {% if messages %}
          {% for message in messages %}
          <div class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissable">
              <strong>{{ message }}</strong>
            </div>
          </div>
          {% endfor %}
      {% endif %}
    </div>

    {% block content %}
    {% endblock content %}
    
    {% include 'footer.html' %}
  
    {% include 'scripts.html' %}

    {% block scripts %}
    {% endblock scripts %}

  </body>
</html>

ecomm/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1 class="mb-4 ml-2">Contact Us</h1>

    <p class="ml-2">If you have any questions or inquiries, please feel free to get in touch with us using the information below:</p>

    <ul class="mb-4 ml-4">
        <li>Email: example@example.com</li>
        <li>Phone: 123-456-7890</li>
        <li>Address: 123 Main Street, City, Country</li>
    </ul>

    <p class="ml-2">We look forward to hearing from you!</p>
{% endblock %}

ecomm/templates/footer.html
<footer class="text-center text-white mt-4" style="background-color: rgb(49, 68, 117)">
    <hr class="text-dark">
    
    <div class="container">
      <!-- Section: Social media -->
      <section class="mb-3">
        
        <!-- Facebook -->
        <a
          class="btn-link btn-floating btn-lg text-white"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark">
          <i class="fab fa-facebook-f"></i>
        </a>
  
        <!-- Twitter -->
        <a
          class="btn-link btn-floating btn-lg text-white"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i></a>
  
        <!-- Google -->
        <a
          class="btn-link btn-floating btn-lg text-white"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a
          class="btn-link btn-floating btn-lg text-white"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- YouTube -->
        <a
          class="btn-link btn-floating btn-lg text-white"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-youtube"></i
        ></a>
        <!-- Github -->
        <a
          class="btn-link btn-floating btn-lg text-white"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); text-color: #E0E0E0">
      © <script>document.write(new Date().getFullYear());</script>
      | This website is made with <i class="fas fa-heart text-danger"></i>
    </div>
    <!-- Copyright -->
  </footer>
  

ecomm/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% include 'carousel.html' %}



<!--Main layout-->
<main>
    <div class="container">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: rgb(49, 68, 117)" >
            <!-- Container wrapper -->
            <div class="container-fluid ">

                <!-- Navbar brand -->
                <a class="navbar-brand" href="{% url 'toko:home-produk-list' %}"
                  ><span style="color: rgb(255, 255, 255); font-weight: bold">Cate</span
                  ><span style="color: #96bbe8; font-weight: bold">gories:</span>
                 </a>

                <!-- Toggle button -->
                <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent2"
                        aria-controls="navbarSupportedContent2"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
  
                        <!-- Link -->

                        <li class="nav-item">
                          <a class="nav-link text-white" href="{% url 'toko:home_category' 'S' %}">Shirt</a>
                      </li>

                      <!-- Link to filter by sport wears category -->
                      <li class="nav-item">
                          <a class="nav-link text-white" href="{% url 'toko:home_category' 'D' %}">Dress</a>
                      </li>

                      <!-- Link to filter by outwears category -->
                      <li class="nav-item">
                          <a class="nav-link text-white" href="{% url 'toko:home_category' 'SW' %}">Sweatshirt</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link text-white" href="{% url 'toko:home_category' 'C' %}">Pants</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'toko:home_category' 'Pl' %}">Playsuit & Jumpsuit</a>
                    </li>
  

                    </ul>

                    <!-- Search -->
                    <form class="w-auto py-1" style="max-width: 12rem">
                        <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search">
                    </form>

                </div>
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

        <!-- Products -->
        <section>
            <div class="text-center">
              <div class="row">
                
                {% for pItem in object_list %}
                <div class="col-lg-3 col-md-6 mb-4">
                  <div class="card">
                    <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                      data-mdb-ripple-color="light">
                      <img src="{{ pItem.gambar.url }}"
                        class="w-100" />
                      <a href="{{ pItem.get_absolute_url }}"> 
                        <div class="mask">
                          <div class="d-flex justify-content-start align-items-end h-100">
                            <h5><span class="badge bg-{{ pItem.get_label_display }} ms-2">{{ pItem.label }}</span></h5>
                          </div>
                        </div>
                        <div class="hover-overlay">
                          <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                        </div>
                      </a>
                    </div>
                    <div class="card-body">
                      <a href="{{ pItem.get_absolute_url }}" class="text-reset">
                        <h5 class="card-title mb-2">{{ pItem.nama_produk }}</h5>
                      </a>
                      <a href="" class="text-reset ">
                        <p>{{ pItem.get_kategori_display }}</p>
                      </a>
                      <div class="ratting mt-2" style=" color: #fcd34d">
                        <i class='fas fa-star'></i>
                        <i class='fas fa-star'></i>
                        <i class='fas fa-star'></i>
                        <i class='fas fa-star'></i>
                        <i class='fas fa-star'></i>
                      </div>
                      <!-- <p class="mb-3 price">Rp.{% if pItem.harga_diskon %}{{ pItem.harga_diskon }}{% else %}{{ pItem.harga }}{% endif %}</p> -->
                      {% if pItem.harga_diskon %}
                        <div class="mb-3 price me-1" style="font-size: 18px;">
                         <p class="text-gray-500 flex items-center me-2"> 
                           <del>Rp.{{ pItem.harga }} </del>
                           <span class="mr-4 percentage" style="font-size: 15px;">-{{ pItem.discount_percentage }}%</span>
                           <span class="ml-3 mt-1 py-0.5 px-2 inline-block border-2 border-red bx bxs-discount diskon" style="color: #b70808"><strong>Rp. {{ pItem.harga_diskon }}</strong>
                          </span>
                         </p>
                        </div>
                      {% else %}
                        <p class="mb-3" style="font-size: 18px;">Rp.{{ pItem.harga }}</p>
                      {% endif %}
                    
                    
                    
                    </div>
                  </div>
                </div>
                {% empty %}
                  <p>Data Produk belum tersedia</p>
                {% endfor %}

              </div>
            </div>
          </section>
        <!-- End Products -->

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
            <ul class="pagination">
                <li class="page-item">
                  {% if page_obj.has_previous %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                  {% endif %}
                </li>
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                <li class="page-item">
                  {% if page_obj.has_next %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                  {% endif %}
                </li>
            </ul>
        </nav>
        {% endif %}
        <!-- Pagination -->
    </div>
</main>
<!--Main layout-->
{% endblock content %}

ecomm/templates/navbar.html
{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
    <!-- Container wrapper -->
    <div class="container">    
        <!-- Toggle button -->
        <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent1"
        aria-controls="navbarSupportedContent1"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
        <i class="fas fa-bars"></i>
        </button>
    
        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">      
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-sm-0" href="#">
            <img
            src="https://uploads-member.evosesports.com/AcSsF48rcB4t95deVSHQ.gif"
            height="20"
            alt="MDB Logo"
            loading="lazy"
            />
        </a>
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
            <a class="nav-link " href="{% url 'toko:home-produk-list' %}">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'toko:checkout' %}">Checkout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'toko:contact' %}">Contact</a>
                </li>
        </ul>
        <!-- Left links -->      
        </div>
        <!-- Collapsible wrapper -->
        
        <!-- Right elements -->
        <div class="d-flex align-items-center">
            {% if request.user.is_authenticated %}
                <!-- Icon -->
                <a class="nav-link me-3" href="{% url 'toko:order-summary' %}">
                    <i class="fas fa-shopping-cart"></i>
                    <span class="badge rounded-pill badge-notification bg-danger">{{ request.user|total_produk_dikeranjang }}</span>
                </a>
                <ul class="navbar-nav">
                <!-- Avatar -->
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarDropdownMenuLink"
                    role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img (31).webp" class="rounded-circle"
                    height="22" alt="Avatar" loading="lazy" />
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                </ul>
                </li>
                </ul>
                <!-- <a class="nav-link me-3" href="{% url 'account_logout' %}">
                    <i class="fas fa-right-from-bracket"></i> -->
                </a>
            {% else %}
                <a class="nav-link me-3" href="{% url 'account_login' %}">
                <i class="fas fa-right-to-bracket"></i>
            {% endif %}
        </div> 
        <!-- Right elements -->
        
    </div>
    <!-- Container wrapper -->
</nav>
    <!-- Navbar -->

ecomm/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 mt-4 mb-4">
            <h1 class="text-center">Order Summary</h1>
        </div>
    </div>
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
        <tr>
            <th>#</th>
            <th>Nama Produk</th>
            <th>Harga</th>
            <th>Quantity</th>
            <th>Total Harga</th>
        </tr>
        </thead>
        <tbody>
            {% for pItem in keranjang.produk_items.all %}
            <tr>
                <td scope="row">
                    {{ forloop.counter }}
                </td>
                <td>
                    <a href="{% url 'toko:produk-detail' pItem.produk_item.slug %}">
                        <div class="d-flex align-items-center">
                            <img
                                src="{{ pItem.produk_item.gambar.url }}"
                                alt=""
                                style="width: 45px; height: 45px"
                                class="rounded-circle"
                                />
                            <div class="ms-3">
                            <p class="fw-bold mb-1">{{ pItem.produk_item.nama_produk }}</p>
                            <p class="text-muted mb-0"> {{ pItem.produk_item.deskripsi|truncatewords:10 }}</p>
                            </div>
                        </div>
                    </a>
                </td>
                <td>
                    <div>Rp.
                        {% if pItem.produk_item.harga_diskon %}
                        {{ pItem.produk_item.harga_diskon }}
                        {% else %}
                        {{ pItem.produk_item.harga }}
                        {% endif %}
                    </div>
                </td>
                <td>
                    <div class="input-group">
                        <span class="input-group-btn">
                            <a href="{% url 'toko:remove-from-cart' pItem.produk_item.slug %}" class="btn btn-outline-secondary btn-minus">-</a>
                        </span>
                        {{ pItem.quantity }}
                        <span class="input-group-btn">
                            <a href="{% url 'toko:add-to-cart' pItem.produk_item.slug %}" class="btn btn-outline-secondary btn-plus">+</a>
                        </span>
                    </div>
                </td>
                <td>                
                    {% if pItem.produk_item.harga_diskon %}
                    Rp.{{ pItem.get_total_harga_diskon_item }}
                    <span class="badge badge-danger rounded-pill d-inline">Hemat Rp.{{ pItem.get_total_hemat_item }}</span>
                    {% else %}
                    Rp.{{ pItem.get_total_harga_item }}
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan='5'>Keranjang kosong</td>
            </tr>
            <tr>
                <td colspan="5">
                <a class="btn btn-primary float-end" href="{% url 'toko:home-produk-list' %}">Lanjut belanja</a>
                </td>
            </tr>
            {% endfor %}

            {% if keranjang.get_total_harga_order %}
            <tr>
                <td colspan="4"><b>Total Belanja</b></td>
                <td><b>Rp.{{ keranjang.get_total_harga_order }}</b>
                    {% if keranjang.get_total_hemat_order %}
                    <span class="badge badge-danger">Hemat Rp.{{ keranjang.get_total_hemat_order }}</span>
                    {% endif %}
                </td>
            </tr>

            <tr>
                <td colspan="5">
                <a class='btn btn-info float-end ml-2' href="{% url 'toko:checkout' %}">Checkout</a>
                <a class='btn btn-danger' href="{% url 'toko:home-produk-list' %}">Lanjut belanja</a>
                </td>
            </tr>
            {% endif %}
        </tbody>
  </table>
</div>
{% endblock content %}

ecomm/templates/payment.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="d-flex justify-content-center">
    <div class="row justify-content-center">
      <div class="col pt-5 pb-5">
        <p>Total belanjaan kamu : <strong>${{ order.get_total_harga_order }}</strong></p>
        <br />
        {% if is_paypal %}
        <div>{{ paypalform.render }}</div>
        {% else %}
        <div>Pembayaran Strip belum diaktifkan gunakan Paypal</div>
        <a href="{% url 'toko:payment' 'paypal' %}"><div class="btn btn-info">Paypal</div></a>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}

ecomm/templates/product_detail.html
{% extends 'base.html' %}

{% block content%}

<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container mt-5">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <img src="{{ object.gambar.url }}" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <!--Content-->
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                            <span class="badge bg-dark me-1">{{ object.get_kategori_display }}</span>
                        </a>
                        {% if object.label == 'NEW' %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">New</span>
                        </a>
                        {% elif object.label == 'SALE' %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">Sale</span>
                        </a>
                        {% else %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">Bestseller</span>
                        </a>
                        {% endif %}
                    </div>

                    <strong><p style="font-size: 20px;">{{ object.nama_produk }}</p></strong>

                    <p class="lead">
                        {% if object.harga_diskon %}
                        <span class="me-1">
                            <del>Rp.{{ object.harga }}</del>
                        </span>
                        <span class="mr-4 percentage">-{{ object.discount_percentage }}%</span>
                           <span class="ml-3 mt-1 py-0.5 px-2 flex" style="color: #b70808">Rp. {{ object.harga_diskon }}</span>
                        {% else %}
                        <span>Rp.{{ object.harga }}</span>
                        {% endif %}
                    </p>

                    <div class="ratting" style=" color: #fcd34d">
                        <i class='fas fa-star'></i>
                        <i class='fas fa-star'></i>
                        <i class='fas fa-star'></i>
                        <i class='fas fa-star'></i>
                        <i class='fas fa-star'></i>
                    </div>

                    <strong><p style="font-size: 20px;">Deskripsi</p></strong>

                    <p>{{ object.deskripsi }}</p>
                    <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary ms-1 mt-6">
                        Tambah ke keranjang
                        <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                    <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger ms-1" >
                        Kurangi keranjang
                        <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                </div>
                <!--Content-->
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr />

        

        <!--Grid row-->
        <div class="row">
            <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
                <div class="grid grid-cols-3 gap-3">
                    {% for item in related_items %}
                        <div>
                            <a href="{{ item.get_absolute_url }}">
                                <div>
                                    <img src="{{ item.gambar.url }}" class="rounded-t-xl">
                                </div>
                                <div class="p-6 bg-white rounded-b-xl">
                                    <h2 class="text-2xl">{{ item.nama_produk }}</h2>
                                    <p class="text-gray-500">Rp. {{ item.harga }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->

{% endblock content%}

ecomm/templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>